FROM airbyte/destination-mssql:2.2.22
LABEL org.opencontainers.image.source="https://github.com/anime-shed/airbyte"
COPY connector.jar /airbyte/lib/io.airbyte.airbyte-integrations.connectors-destination-mssql.jar
