FROM airbyte/source-mssql:5.0.1
LABEL org.opencontainers.image.source="https://github.com/anime-shed/airbyte"
COPY connector.jar /airbyte/lib/io.airbyte.airbyte-integrations.connectors-source-mssql.jar
